version: '3.4'

services:
  playerapplication:
    image: ${DOCKER_REGISTRY-}playerapplication
    build:
      context: .
      dockerfile: PlayerApplication/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - playerapplication-network
    depends_on:
      playerapplication.database:
        condition: service_healthy
  playerapplication.database:
    container_name: "playerapplication.database" # host url for my postgres db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - playerapplication-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  playerapplication-network:
    driver: bridge
